### ISSUE TITLE
no graph created

### ISSUE THREAD

**Issue by tommy-dev** [igrigorik/decisiontree#25]
Generally everything works fine, but this is not creating any graph. I use the example code from the blog article, no effect, no error, application puts the result but is not creating any png file.

**Comment by igrigorik** [comment]
Can you share the code?

**Comment by tommy-dev** [comment]
I solved it already, I added a graphviz gem, but forgot to additionally install it. Now everything works fine. Sorry for this issue

**Comment by igrigorik** [comment]
glad to hear!
