### ISSUE TITLE
Ruby ML list

### ISSUE THREAD

**Issue by arbox** [igrigorik/decisiontree#37]
Dear Ilya,

we've recently added your `decisiontree` to our Awesome RubyML list:  https://github.com/arbox/machine-learning-with-ruby

Your project is really important for the Ruby ML ecosystem. So we introduced the `rubyml` topic which will ideally connect all ML related projects written in and for Ruby on GitHub.

Please consider adding the `rubyml` topic to your repository :)

Thank you!

**Comment by igrigorik** [comment]
Done! Thanks for the tip.
